### ISSUE TITLE
NullReferenceException when not adding loggers

### ISSUE THREAD

**Issue by JurgenVandendriessche** [angelsix/dna-framework#1]
If you build the framework without any loggers, the 'Build()' function will fail.

Example:
`new FrameworkConstruction().Build();`

**Comment by angelsix** [comment]
Works fine. What error do you get?

If you are referencing it from a .Net Framework project edit the csproj file and add:

    <RestoreProjectStyle>PackageReference</RestoreProjectStyle>

Otherwise the package restore doesn't restore the packages correctly until VS update their template and framework to correct this

**Comment by angelsix** [comment]
Fixed this but just away on business now for a week I'll push the fix on Sunday when I'm back and just close this issue for now as it's fixed then if you find issue after the next push you can re open a ticket
