### ISSUE TITLE
LogLevel not present in logfile

### ISSUE THREAD

**Issue by predtr** [angelsix/dna-framework#11]
Hi,

I use your framework on many project and I'm almost fully satisfy of it. You did a great job.

My last point of disappointment is the fact that we don't log the log level on the log file. Why you don't use them on the log file ?

Or may we can and I don't understand how to activate them. 

Anyway great job and thank you.

**Comment by angelsix** [comment]
Yes I should probably add that to the FileLogger. I've done it now https://github.com/angelsix/dna-framework/commit/2333641d1f5cb40a41040d1b53a4e337c807f520so if you update to 1.0.7.15 you will get the log level output. You can disable it via the constructor of the FileLogger in configuration class.
