### ISSUE TITLE
HttpEndpointChecker Bug

### ISSUE THREAD

**Issue by NadirTennci** [angelsix/dna-framework#13]
Hi, 

when I was testing the HttpEndpointChecker I found that when the app is launched offline the HttpEndpointChecker doesnt fire the "stateChangedCallback", hence the app wont be aware that it's offline and the offline bar wont show after setting the offline bar to Collapsed by default (Online by default), I digged in the Framework code and I found that this boolean is set to false by default:

public bool Responsive { get; set; }

Therefor the event doesnt fire.

if (responsive != Responsive)
{
         Responsive = responsive;
         mStateChangedCallback?.Invoke(responsive);
}

A possible solution to this is to simply set Responsive to "null" and add a condition "Responsive != null" next to the "responsive != Responsive"

Thank you for reading this.

**Comment by angelsix** [comment]
Thanks. Check if this fixes it **https://github.com/angelsix/dna-framework/commit/0dd2a9202a5554325f3c615c3f2b54a455194d7d**

**Comment by NadirTennci** [comment]
Hi, Are you willing to release the fix on the next update on the NuGet package manager? I prefer not to use the source code directly to be up to date with the Dna Framework without updating it manually.

PS: Thank you so much for your work, especially the Dna Framework, I love it and I'll use it on all my future projects.

**Comment by angelsix** [comment]
Yes I'll be working on updates to this soon so this will appear in the next update.
