### ISSUE TITLE
IsDevelopment always false in NuGet package

### ISSUE THREAD

**Issue by JurgenVandendriessche** [angelsix/dna-framework#2]
When calling `Framework.Environment.IsDevelopment` always returns false:
The #if RELEASE is checked when the NuGet package is compiled.

The best solution I found was making a method that sets the IsDevelopment with a conditional attribute and calling that method from outside the NuGet Package.

`[Conditional("DEBUG")]`
 `public void SetIsDevelopment() => IsDevelopment = true;`

But this only works if you call the method from outside the NuGet Package, otherwise it will not work.

**Comment by angelsix** [comment]
When I did a quick test (just referencing the dll when compiled and not a local nuget) I actually get the opposite behaviour it's only working when inside the original project. I'll do some proper checks and work on it this week

**Comment by angelsix** [comment]
Ok so the best I could come up with that works both in source code and in nuget package environments, as well as maintaining flexibility on when we consider being in a *Development* environment I have done the following.

https://github.com/angelsix/dna-framework/commit/9c46862ac54de22b5fed338cdfbff95c4662cc10

So now inside source (if you reference `Dna.Framework.csproj` directly in your project, nothing changes:

```
new DefaultFrameworkConstruction().Build();

var inDevelopment = Framework.Environment.IsDevelopment;
```

If you are referencing `Dna.Framework` via NuGet package reference you have one extra step.

```
new DefaultFrameworkConstruction().Build();
Framework.SetEnvironment();

var inDevelopment = Framework.Environment.IsDevelopment;
```

And you are also free to manually set `Framework.Environment.IsDevelopment = true`

New package is out now on NuGet `1.0.5.0` if you want to test it.

**Comment by JurgenVandendriessche** [comment]
I finaly found the solution that gives the result i want in my project.

`IsDevelopment = !Assembly.GetEntryAssembly().GetCustomAttribute<DebuggableAttribute>().IsJITTrackingEnabled;`

[Original code](https://stackoverflow.com/questions/2186613/how-to-check-if-an-assembly-was-built-using-debug-or-release-configuration)

NOTE: I didn't include a null check to the [ Assembly.GetEntryAssembly()](https://msdn.microsoft.com/en-us/library/system.reflection.assembly.getentryassembly(v=vs.110).aspx)

I hope this helps you

**Comment by angelsix** [comment]
That's a good idea. That actually makes good sense too. Thanks for that find. I've merged changes in now https://github.com/angelsix/dna-framework/commit/19036bfa27c49ea573c91d4a686b3cade9827847
