### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Daniel-iel** [angelsix/dna-framework#3]
Hi there,

Where can I find the dna-framework documentation ?

Best regards.

**Comment by angelsix** [comment]
Right now it's still early days. To use it in a normal application (WPF, Console, .Net Core Console... basically anything except ASP.Net Core) you just do:

```
Framework.Construct<DefaultFrameworkConstruction>().AddSomeServices().Build();
```

To add services without extension methods you could do:

```
using Dna;
using Microsoft.Extensions.DependencyInjection;

// This sets Framework.Construction property...
Framework.Construct<DefaultFrameworkConstruction>();

// Now add some services
Framework.Construction.Services.AddSingleton<SomeClass>();

// Now build it
Framework.Construction.Build();

// Now get your service from anywhere with
Framework.Service<SomeClass>();
```

And now your service provider (Dependency injection provider) is `Framework.Provider` and you get get services that have been injected via `Framework.Service<T>()` or `Framework.Provider.GetService<T>`.

Commented here https://github.com/angelsix/dna-framework/blob/master/Source/Dna.Framework/Framework/Construction/DefaultFrameworkConstruction.cs#L19

And to integrate with ASP.Net Core so they share the same provider and collection https://github.com/angelsix/dna-framework/blob/master/Source/Dna.Framework/Framework/Construction/HostedFrameworkConstruction.cs#L21 and video on doing that here https://www.youtube.com/watch?v=lM6GjIQKkUo

I will be doing a video next on Dna Framework on whats currently in it and how to use it in general. I'll keep this open and close it once I've done that video
